services:
  service_a:
    build:
      context: .
      dockerfile: service_a/Dockerfile
    container_name: service_a
    ports:
      - "8000:8000"
    depends_on:
      - service_b

  service_b:
    build:
      context: .
      dockerfile: service_b/Dockerfile
    container_name: service_b
    ports:
      - "8001:8001"


