services:
  service_a:
    image: service_a:latest
    ports:
      - "8000:8000"
    networks:
      - app_net

  service_b:
    image: service_b:latest
    ports:
      - "8001:8001"
    networks:
      - app_net

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - service_a
      - service_b
    networks:
      - app_net

networks:
  app_net:
    external: true
    name: edu_project_devops_app_net
